### ISSUE TITLE
compilation error with arm neon and gcc 11.2.1

### ISSUE THREAD

**Issue by lmarz** [RenderKit/embree#383]
When trying to build embree under aarch64, cmake doesn't detect arm neon and enables the -msse2 flag instead, which causes a compiler error.
gcc does support arm neon though with the header file "arm_neon.h" and the macro __ARM_NEON.

Manually enabling EMBREE_ARM in cmake gives the following error output for the first 4 files:
[build-embree.log](https://github.com/embree/embree/files/8974403/build-embree.log)

embree compiles successfully, when using clang

**Comment by svenwoop** [comment]
Could you please check if this worked with Embree 3.13.3?

**Comment by luyatshimbalanga** [comment]
I confirm the [issue with version 3.13.4](https://koji.fedoraproject.org/koji/taskinfo?taskID=88933013) on aarch64 architecture which suggests a regression compared to the previous version with GCC compiler. 
For references, the listed parameters on the %build section:
```
export CXXFLAGS="%{optflags} -Wl,--as-needed"
%cmake \
	-DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_CXX_STANDARD=17 \
	-DCMAKE_INSTALL_LIBDIR=%{_libdir} \
	-DCMAKE_INSTALL_PREFIX=%{_prefix} \
	-DEMBREE_COMPACT_POLYS=ON \
	-DEMBREE_IGNORE_CMAKE_CXX_FLAGS=OFF \
%if %{with ispc}
        -DEMBREE_ISPC_SUPPORT=ON \
%else
        -DEMBREE_ISPC_SUPPORT=OFF \
%endif
        -DEMBREE_MAX_ISA=DEFAULT \
	-DEMBREE_TUTORIALS=OFF 
```
The macros in `%{...}` are listed under the [Fedora Packaging Guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/RPMMacros/).

**Comment by ppisar** [comment]
I also recommend updating README.md which reads:

      Embree requires at least an x86 CPU with support for
      SSE2 or an Apple M1 CPU.

That's misleading because people think that they need Appli M1 CPU, while a generic AArch64 CPU is enough.

**Comment by StefanBruens** [comment]
The problem is caused by erroneous changes for the Apple silicon support.

The flags are set in e.g. `gnu.cmake`, included here:
https://github.com/embree/embree/blob/489b746c0d5010e0da10345e9dc96768bec9a037/CMakeLists.txt#L255

But for anything but `APPLE`, `EMBREE_ARM` is only set here:
https://github.com/embree/embree/blob/489b746c0d5010e0da10345e9dc96768bec9a037/CMakeLists.txt#L282-L285

I.e. all conditionals depending on `EMBREE_ARM` in `gnu.cmake` are wrong.

**Comment by akien-mga** [comment]
I can confirm the issue in 3.13.5 on Mageia Cauldron aarch64, while 3.13.3 built fine.

I believe this was fixed by https://github.com/embree/embree/commit/82ca6b5ccb7abe0403a658a0e079926478f04cb1, but 3.13.6 was never released with the fix (and now 4.0.0 is a compat breaking update).

**Comment by svenwoop** [comment]
Please just stay on Embree 3.13.3 when you compat with Embree 3 is important. Otherwise switching to Embree 4 should be straight forward.

**Comment by StefanBruens** [comment]
> Please just stay on Embree 3.13.3 when you compat with Embree 3 is important. Otherwise switching to Embree 4 should be straight forward.

The correct answer is "Use Embree 3.13.5 and cherry-pick https://github.com/embree/embree/commit/82ca6b5ccb7abe0403a658a0e079926478f04cb1". Otherwise, one misses the fixes in 3.13.4/3.13.5.

**Comment by StefanBruens** [comment]
Or even simpler, pass `-DEMBREE_ARM=ON` to cmake.
